version: "3.8"
services:
  web:
    container_name: ttd-learnig.test
    build:
      context: .
      dockerfile: dockerfiles/apache.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  #      - /var/www/html/vendor
  #depends_on:
  #- mysql
  mysql:
    container_name: "db_sharedmodules"
    image: mysql:8
    env_file:
      - ./conf/mysql.env
    ports:
      - "3310:3306"
    volumes:
      - dbdata2:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  spark:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/spark"]
  phpunit:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/vendor/bin/phpunit"]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbdata2:
